### ISSUE TITLE
Some entities are not fetched by hass-cli

### ISSUE THREAD

**Issue by haakonstorm** [home-assistant/home-assistant-cli#272] opened 2019-08-23 13:23 UTC
# Some entities (switches) not fetched by hass-cli
 
```
❯ hass-cli --version
hass-cli, version 0.8.0.dev20190820161233
```

- Latest HASSIO on RPI3B+, Zigbee over RaspBee.
- Sonoff BASIC switches (wifi) (multiple).
- Tested with several hass-cli versions, both via `homebrew` and `pip`. 

Running 
`❯ hass-cli --server https://mydomain.duckdns.org --token thetoken --insecure entity list`
**successfully** retrieves entities, but the switches from the [Sonoff component for original firmware](https://github.com/peterbuga/HASS-sonoff-ewelink) do **not** appear in the list. 

Same result for `hass-cli device list`.

**Running a bulk**
`❯ hass-cli ... service call switch.toggle`
**successfully toggles the Sonoff switches** (along with everything else..). Relevant output:

```
   -  attributes:
          device_id: '1000781892'
          friendly_name: onoffD
          rssi: -80
      context:
          id: e56ccc0804b34f29b28b06fa1c25977e
          parent_id:
          user_id: 6077e1d6074c4c8a9103d88b9885ea3a
      entity_id: switch.sonoff_1000781892
      last_changed: '2019-08-23T13:10:33.287095+00:00'
      last_updated: '2019-08-23T13:10:33.287095+00:00'
      state: on
```

# Sonoff component setup

```
username: !secret sonoff_username
password: !secret sonoff_password
scan_interval: 60
grace_period: 600
api_region: 'eu'
entity_prefix: true
debug: false
```

Please advise what I can do to provide more and better debug information.

**Comment by maxandersen** [comment] 2019-08-23 13:25
are they visible in HA entities and/or integration lists in the webui ?

**Comment by haakonstorm** [comment] 2019-08-23 13:25
<img width="748" alt="Screenshot of Brave Browser Beta (23-08-2019, 15-11-50)" src="https://user-images.githubusercontent.com/193781/63595879-47c20f80-c5ba-11e9-9967-943cf40e947f.png">

**Comment by haakonstorm** [comment] 2019-08-23 13:26
<img width="669" alt="Screenshot of Brave Browser Beta (23-08-2019, 15-26-35)" src="https://user-images.githubusercontent.com/193781/63595937-69bb9200-c5ba-11e9-9e89-7f49c1212c26.png">

**Comment by maxandersen** [comment] 2019-08-23 13:47
What if you do "entity list onoff" what is the output ?

How many entities do you have in total ?

**Comment by haakonstorm** [comment] 2019-08-23 14:04
Nope :/

```
❯ hass-cli ... entity list onoff
ENTITY_ID    NAME    DEVICE_ID    PLATFORM    CONFIG_ENTRY_ID    DISABLED_BY

~
❯
```

Not really sure about the exact amount of devices, but this might help?
```
❯ ha entity list|wc -l
     270

~
❯ ha device list|wc -l
     103
```

**Comment by haakonstorm** [comment] 2019-08-24 12:03
# UPDATE - more missing entities

There are other missing entities/devices that do not appear with `hass-cli` but do in the Developer section of Home Assistant. 

This is 
- a `device_tracker` for my car (which has an API), as well as 
- a `Geolocation` translation from the device_tracker GPS lat/lon to human-readable street address, which creates a `sensor.` entity.

```
~/Downloads
❯ ha entity list device_tracker
ENTITY_ID                                NAME    DEVICE_ID                         PLATFORM    CONFIG_ENTRY_ID                   DISABLED_BY
device_tracker.stormfonx256              None    7d130ea0eccd478d944ec9f23eb642e7  mobile_app  966c09a0c1c74680871b16abf4648128  None
device_tracker.stormfonx256_2            None    6db7c0cc605f49ddb1599d92ba31e2a1  mobile_app  e7d91054ce81406d9ae0b7be12d4f416  None
device_tracker.stormpadpro_2             None    2f7c8cb583404331b40198130a260f14  mobile_app  5c3dd9943e634b1ba994c4d6b45ae4eb  None
device_tracker.stormpadpro_3             None    e4f1a1c7e2a24f6fa49b803e9de60a02  mobile_app  564208d46d07472cbb55250e426756df  None
device_tracker.stormfonx256_hassapp_ios  None    9095ebe77e644b3db724dcdd5ee496f7  mobile_app  d93536935440414d9c7a312566791a61  None

~/Downloads
❯ ha entity list sensor.tesla
ENTITY_ID                                         NAME    DEVICE_ID    PLATFORM    CONFIG_ENTRY_ID    DISABLED_BY
binary_sensor.tesla_model_x_charger_sensor        None    None         tesla       None               None
binary_sensor.tesla_model_x_parking_brake_sensor  None    None         tesla       None               None
sensor.tesla_model_x_temperature_sensor_inside    None    None         tesla       None               None
sensor.tesla_model_x_temperature_sensor_outside   None    None         tesla       None               None
sensor.tesla_model_x_mileage_sensor               None    None         tesla       None               None
sensor.tesla_model_x_battery_sensor               None    None         tesla       None               None
sensor.tesla_model_x_range_sensor                 None    None         tesla       None               None

~/Downloads
❯
```

# output from `hass-cli`
<img width="378" alt="Screenshot of Snagit 2019 (24-08-2019, 13-57-36)" src="https://user-images.githubusercontent.com/193781/63636997-88339300-c677-11e9-911f-c33ad139212f.png">

# device_tracker.my_car in HASS
<img width="1147" alt="Screenshot of Snagit 2019 (24-08-2019, 13-55-54)" src="https://user-images.githubusercontent.com/193781/63636999-92559180-c677-11e9-86eb-54caa97d7186.png">

# sensor.tesla in HASS
<img width="1133" alt="Screenshot of Snagit 2019 (24-08-2019, 13-54-45)" src="https://user-images.githubusercontent.com/193781/63637002-941f5500-c677-11e9-94a7-9daf2c472442.png">

**Comment by maxandersen** [comment] 2019-08-25 09:01
I got no good explanation why those entries should be missing - hass-cli just parses the returned output from an api call which (in theory) should be the exact same the frontend uses.

**Comment by maxandersen** [comment] 2019-08-25 09:21
Just to state the obvious - you are sure you dont access a different homeassistant instance ?
I had that happen to me as the autodeteCtion picked up my test Instance over myprod one.

And yes it's a long shot....just want to be sure we exclude all stupid possible reasons :)

**Comment by haakonstorm** [comment] 2019-08-26 18:42
This alfred workflow returns all entities!
https://github.com/Skakiz/Alfred-Home-assistant-workflow
See if there is anything to grab from there?

**Comment by maxandersen** [comment] 2019-08-26 20:02
> See if there is anything to grab from there?

that code looks like its calling the exact same apis :/ 

One thing you can do is to call hass-cli with `-o json -verbose -debug` and you should if I recall get the raw output as sent over the wire ....the data must be in there if the alfred workflow and browser works ...

**Comment by haakonstorm** [comment] 2019-08-27 10:32
It might be that I've got problems with the Alfred Workflow as in fact it appears to be using cached records, I'm looking into it.

Is there any cache that I need to flush for the API / hass-cli?

Filed here as well:
https://community.home-assistant.io/t/missing-injected-entities-from-api/134099

**Comment by maxandersen** [comment] 2019-08-27 10:53
Hass-cli intentionally do not have any caches so nothing to clear here.

**Comment by maxandersen** [comment] 2019-08-27 10:56
If you are ok with it you share (in private ) a set of credentials to your server and I can explore and see how I can reproduce. Won't be able to do that before thursday though.

**Comment by haakonstorm** [comment] 2019-08-28 11:48
Hey, that would be awesome! I took the liberty to email you the details :)

**Comment by maxandersen** [comment] 2019-08-30 12:47
thanks for giving me access - turns out the "error" is all mine for forgetting the recent change in semantics of hass-cli to match homeassistant :)

entity != state of entity.

use `hass-cli state list sonof` to get the states. Those matches what you find in the web ui.

**Comment by maxandersen** [comment] 2019-08-30 12:51
closing this as "not a bug", reopen if you still see an issue.

**Closed by maxandersen** 2019-08-30 12:51 UTC
